site_name: Alternatives
copyright: Copyright 2023 MicrocontrollersDev

theme:
  favicon: assets/images/logo.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - toc.integrate
    - content.code.annotate
  name: material
  logo: assets/images/logo.png
  icon:
    repo: fontawesome/brands/github
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: purple
    accent: indigo
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: purple
    accent: indigo
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode

repo_name: Alternatives
repo_url: https://github.com/MicrocontrollersDev/Alternatives
edit_uri: ../Alternatives/edit/main/docs/
extra:
  social:
    - icon: simple/modrinth
      link: https://modrinth.com/user/Microcontrollers
    - icon: fontawesome/brands/github
      link: https://github.com/MicrocontrollersDev/Alternatives
    - icon: simple/revolt.chat
      link: https://rvlt.gg/vNMTy2bw
    - icon: fontawesome/brands/discord
      link: https://discord.gg/rejfv9kFJj
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@Microcontrollers
    - icon: fontawesome/brands/patreon
      link: https://www.patreon.com/Microcontrollers

nav:
  - "Home":
      - "Welcome": "index.md"
      - "Contributors": "contributors.md"
  - "1.8.9":
      - "Home": "1.8.9/home.md"
      - "Clients":
        - "Badlion Client": "1.8.9/badlion_client.md"
        - "Feather Client": "1.8.9/feather_client.md"
        - "Hyperium": "1.8.9/hyperium.md"
        - "LabyMod": "1.8.9/labymod.md"
        - "Lunar Client": "1.8.9/lunar_client.md"
      - "Mods":
          - "5zig": "1.8.9/5zig.md"
          - "Dungeon Utilities": "1.8.9/dungeon_utilities.md"
          - "HyChat": "1.8.9/hychat.md"
          - "SkyblockCatia": "1.8.9/skyblockcatia.md"
          - "SkyblockExtras": "1.8.9/skyblockextras.md"
          - "Skyblock Reinvented": "1.8.9/skyblock_reinvented.md"
          - "Skypixel": "1.8.9/skypixel.md"
          - "SoopyAddons": "1.8.9/soopy.md"
          - "Wyvtils": "1.8.9/wyvtils.md"
      - "Modpacks":
          - "Refraction v4": "1.8.9/refraction_v4.md"
      - "Other":
          - "Mod List": "1.8.9/modlist.md"
  - "Latest":
      - "Home": "latest/home.md"
      - "Clients":
          - "Badlion Client": "latest/badlion.md"
          - "Feather Client": "latest/feather.md"
          - "Lunar Client": "latest/lunar.md"
      - "Mods":
          - "OptiFine": "latest/optifine.md"
          - "Patcher": "latest/patcher.md"
      - "Other":
          - "Migrating to Latest": "latest/migrating.md"
  - "Launcher":
      - "Home": "launcher/home.md" 
      - "Modrinth App":
          - "Windows": "launcher/modrinth_win.md"
      - "Prism Launcher":
          - "Windows": "launcher/prism_win.md"
          - "MacOS": "launcher/prism_mac.md"
          - "Linux": "launcher/prism_gnu.md"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - toc:
      permalink: true
